/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.13.3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { UseQueryOptions, useQuery } from "react-query";
import { Duration, PreProposeInfo, Admin, Uint128, Binary, VotingStrategy, PercentageThreshold, Decimal, InstantiateMsg, ModuleInstantiateInfo, Coin, VetoConfig, ExecuteMsg, CosmosMsgForEmpty, BankMsg, StakingMsg, DistributionMsg, IbcMsg, Timestamp, Uint64, WasmMsg, GovMsg, VoteOption, MultipleChoiceProposeMsg, MultipleChoiceOptions, MultipleChoiceOption, Empty, IbcTimeout, IbcTimeoutBlock, WeightedVoteOption, MultipleChoiceAutoVote, MultipleChoiceVote, QueryMsg, MigrateMsg, Addr, Config, NullableAddr, VoteResponse, VoteInfo, InfoResponse, ContractVersion, MultipleChoiceOptionType, Expiration, Status, ProposalListResponse, ProposalResponse, MultipleChoiceProposal, CheckedMultipleChoiceOption, MultipleChoiceVotes, VoteListResponse, ProposalCreationPolicy, HooksResponse } from "./DaoContracts.types";
import { DaoContractsQueryClient } from "./DaoContracts.client";
export const daoContractsQueryKeys = {
  contract: ([{
    contract: "daoContracts"
  }] as const),
  address: (contractAddress: string) => ([{
    ...daoContractsQueryKeys.contract[0],
    address: contractAddress
  }] as const),
  config: (contractAddress: string, args?: Record<string, unknown>) => ([{
    ...daoContractsQueryKeys.address(contractAddress)[0],
    method: "config",
    args
  }] as const),
  proposal: (contractAddress: string, args?: Record<string, unknown>) => ([{
    ...daoContractsQueryKeys.address(contractAddress)[0],
    method: "proposal",
    args
  }] as const),
  listProposals: (contractAddress: string, args?: Record<string, unknown>) => ([{
    ...daoContractsQueryKeys.address(contractAddress)[0],
    method: "list_proposals",
    args
  }] as const),
  reverseProposals: (contractAddress: string, args?: Record<string, unknown>) => ([{
    ...daoContractsQueryKeys.address(contractAddress)[0],
    method: "reverse_proposals",
    args
  }] as const),
  getVote: (contractAddress: string, args?: Record<string, unknown>) => ([{
    ...daoContractsQueryKeys.address(contractAddress)[0],
    method: "get_vote",
    args
  }] as const),
  listVotes: (contractAddress: string, args?: Record<string, unknown>) => ([{
    ...daoContractsQueryKeys.address(contractAddress)[0],
    method: "list_votes",
    args
  }] as const),
  proposalCount: (contractAddress: string, args?: Record<string, unknown>) => ([{
    ...daoContractsQueryKeys.address(contractAddress)[0],
    method: "proposal_count",
    args
  }] as const),
  proposalCreationPolicy: (contractAddress: string, args?: Record<string, unknown>) => ([{
    ...daoContractsQueryKeys.address(contractAddress)[0],
    method: "proposal_creation_policy",
    args
  }] as const),
  delegationModule: (contractAddress: string, args?: Record<string, unknown>) => ([{
    ...daoContractsQueryKeys.address(contractAddress)[0],
    method: "delegation_module",
    args
  }] as const),
  proposalHooks: (contractAddress: string, args?: Record<string, unknown>) => ([{
    ...daoContractsQueryKeys.address(contractAddress)[0],
    method: "proposal_hooks",
    args
  }] as const),
  voteHooks: (contractAddress: string, args?: Record<string, unknown>) => ([{
    ...daoContractsQueryKeys.address(contractAddress)[0],
    method: "vote_hooks",
    args
  }] as const),
  dao: (contractAddress: string, args?: Record<string, unknown>) => ([{
    ...daoContractsQueryKeys.address(contractAddress)[0],
    method: "dao",
    args
  }] as const),
  info: (contractAddress: string, args?: Record<string, unknown>) => ([{
    ...daoContractsQueryKeys.address(contractAddress)[0],
    method: "info",
    args
  }] as const),
  nextProposalId: (contractAddress: string, args?: Record<string, unknown>) => ([{
    ...daoContractsQueryKeys.address(contractAddress)[0],
    method: "next_proposal_id",
    args
  }] as const)
};
export const daoContractsQueries = {
  config: <TData = Config,>({
    client,
    options
  }: DaoContractsConfigQuery<TData>): UseQueryOptions<Config, Error, TData> => ({
    queryKey: daoContractsQueryKeys.config(client?.contractAddress),
    queryFn: () => client.config(),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  proposal: <TData = ProposalResponse,>({
    client,
    args,
    options
  }: DaoContractsProposalQuery<TData>): UseQueryOptions<ProposalResponse, Error, TData> => ({
    queryKey: daoContractsQueryKeys.proposal(client?.contractAddress, args),
    queryFn: () => client.proposal({
      proposalId: args.proposalId
    }),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  listProposals: <TData = ProposalListResponse,>({
    client,
    args,
    options
  }: DaoContractsListProposalsQuery<TData>): UseQueryOptions<ProposalListResponse, Error, TData> => ({
    queryKey: daoContractsQueryKeys.listProposals(client?.contractAddress, args),
    queryFn: () => client.listProposals({
      limit: args.limit,
      startAfter: args.startAfter
    }),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  reverseProposals: <TData = ProposalListResponse,>({
    client,
    args,
    options
  }: DaoContractsReverseProposalsQuery<TData>): UseQueryOptions<ProposalListResponse, Error, TData> => ({
    queryKey: daoContractsQueryKeys.reverseProposals(client?.contractAddress, args),
    queryFn: () => client.reverseProposals({
      limit: args.limit,
      startBefore: args.startBefore
    }),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  getVote: <TData = VoteResponse,>({
    client,
    args,
    options
  }: DaoContractsGetVoteQuery<TData>): UseQueryOptions<VoteResponse, Error, TData> => ({
    queryKey: daoContractsQueryKeys.getVote(client?.contractAddress, args),
    queryFn: () => client.getVote({
      proposalId: args.proposalId,
      voter: args.voter
    }),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  listVotes: <TData = VoteListResponse,>({
    client,
    args,
    options
  }: DaoContractsListVotesQuery<TData>): UseQueryOptions<VoteListResponse, Error, TData> => ({
    queryKey: daoContractsQueryKeys.listVotes(client?.contractAddress, args),
    queryFn: () => client.listVotes({
      limit: args.limit,
      proposalId: args.proposalId,
      startAfter: args.startAfter
    }),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  proposalCount: <TData = Uint64,>({
    client,
    options
  }: DaoContractsProposalCountQuery<TData>): UseQueryOptions<Uint64, Error, TData> => ({
    queryKey: daoContractsQueryKeys.proposalCount(client?.contractAddress),
    queryFn: () => client.proposalCount(),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  proposalCreationPolicy: <TData = ProposalCreationPolicy,>({
    client,
    options
  }: DaoContractsProposalCreationPolicyQuery<TData>): UseQueryOptions<ProposalCreationPolicy, Error, TData> => ({
    queryKey: daoContractsQueryKeys.proposalCreationPolicy(client?.contractAddress),
    queryFn: () => client.proposalCreationPolicy(),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  delegationModule: <TData = NullableAddr,>({
    client,
    options
  }: DaoContractsDelegationModuleQuery<TData>): UseQueryOptions<NullableAddr, Error, TData> => ({
    queryKey: daoContractsQueryKeys.delegationModule(client?.contractAddress),
    queryFn: () => client.delegationModule(),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  proposalHooks: <TData = HooksResponse,>({
    client,
    options
  }: DaoContractsProposalHooksQuery<TData>): UseQueryOptions<HooksResponse, Error, TData> => ({
    queryKey: daoContractsQueryKeys.proposalHooks(client?.contractAddress),
    queryFn: () => client.proposalHooks(),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  voteHooks: <TData = HooksResponse,>({
    client,
    options
  }: DaoContractsVoteHooksQuery<TData>): UseQueryOptions<HooksResponse, Error, TData> => ({
    queryKey: daoContractsQueryKeys.voteHooks(client?.contractAddress),
    queryFn: () => client.voteHooks(),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  dao: <TData = Addr,>({
    client,
    options
  }: DaoContractsDaoQuery<TData>): UseQueryOptions<Addr, Error, TData> => ({
    queryKey: daoContractsQueryKeys.dao(client?.contractAddress),
    queryFn: () => client.dao(),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  info: <TData = InfoResponse,>({
    client,
    options
  }: DaoContractsInfoQuery<TData>): UseQueryOptions<InfoResponse, Error, TData> => ({
    queryKey: daoContractsQueryKeys.info(client?.contractAddress),
    queryFn: () => client.info(),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  nextProposalId: <TData = Uint64,>({
    client,
    options
  }: DaoContractsNextProposalIdQuery<TData>): UseQueryOptions<Uint64, Error, TData> => ({
    queryKey: daoContractsQueryKeys.nextProposalId(client?.contractAddress),
    queryFn: () => client.nextProposalId(),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  })
};
export interface DaoContractsReactQuery<TResponse, TData = TResponse> {
  client: DaoContractsQueryClient;
  options?: UseQueryOptions<TResponse, Error, TData>;
}
export interface DaoContractsNextProposalIdQuery<TData> extends DaoContractsReactQuery<Uint64, TData> {}
export function useDaoContractsNextProposalIdQuery<TData = Uint64>({
  client,
  options
}: DaoContractsNextProposalIdQuery<TData>) {
  return useQuery<Uint64, Error, TData>(daoContractsQueryKeys.nextProposalId(client.contractAddress), () => client.nextProposalId(), options);
}
export interface DaoContractsInfoQuery<TData> extends DaoContractsReactQuery<InfoResponse, TData> {}
export function useDaoContractsInfoQuery<TData = InfoResponse>({
  client,
  options
}: DaoContractsInfoQuery<TData>) {
  return useQuery<InfoResponse, Error, TData>(daoContractsQueryKeys.info(client.contractAddress), () => client.info(), options);
}
export interface DaoContractsDaoQuery<TData> extends DaoContractsReactQuery<Addr, TData> {}
export function useDaoContractsDaoQuery<TData = Addr>({
  client,
  options
}: DaoContractsDaoQuery<TData>) {
  return useQuery<Addr, Error, TData>(daoContractsQueryKeys.dao(client.contractAddress), () => client.dao(), options);
}
export interface DaoContractsVoteHooksQuery<TData> extends DaoContractsReactQuery<HooksResponse, TData> {}
export function useDaoContractsVoteHooksQuery<TData = HooksResponse>({
  client,
  options
}: DaoContractsVoteHooksQuery<TData>) {
  return useQuery<HooksResponse, Error, TData>(daoContractsQueryKeys.voteHooks(client.contractAddress), () => client.voteHooks(), options);
}
export interface DaoContractsProposalHooksQuery<TData> extends DaoContractsReactQuery<HooksResponse, TData> {}
export function useDaoContractsProposalHooksQuery<TData = HooksResponse>({
  client,
  options
}: DaoContractsProposalHooksQuery<TData>) {
  return useQuery<HooksResponse, Error, TData>(daoContractsQueryKeys.proposalHooks(client.contractAddress), () => client.proposalHooks(), options);
}
export interface DaoContractsDelegationModuleQuery<TData> extends DaoContractsReactQuery<NullableAddr, TData> {}
export function useDaoContractsDelegationModuleQuery<TData = NullableAddr>({
  client,
  options
}: DaoContractsDelegationModuleQuery<TData>) {
  return useQuery<NullableAddr, Error, TData>(daoContractsQueryKeys.delegationModule(client.contractAddress), () => client.delegationModule(), options);
}
export interface DaoContractsProposalCreationPolicyQuery<TData> extends DaoContractsReactQuery<ProposalCreationPolicy, TData> {}
export function useDaoContractsProposalCreationPolicyQuery<TData = ProposalCreationPolicy>({
  client,
  options
}: DaoContractsProposalCreationPolicyQuery<TData>) {
  return useQuery<ProposalCreationPolicy, Error, TData>(daoContractsQueryKeys.proposalCreationPolicy(client.contractAddress), () => client.proposalCreationPolicy(), options);
}
export interface DaoContractsProposalCountQuery<TData> extends DaoContractsReactQuery<Uint64, TData> {}
export function useDaoContractsProposalCountQuery<TData = Uint64>({
  client,
  options
}: DaoContractsProposalCountQuery<TData>) {
  return useQuery<Uint64, Error, TData>(daoContractsQueryKeys.proposalCount(client.contractAddress), () => client.proposalCount(), options);
}
export interface DaoContractsListVotesQuery<TData> extends DaoContractsReactQuery<VoteListResponse, TData> {
  args: {
    limit?: number;
    proposalId: number;
    startAfter?: string;
  };
}
export function useDaoContractsListVotesQuery<TData = VoteListResponse>({
  client,
  args,
  options
}: DaoContractsListVotesQuery<TData>) {
  return useQuery<VoteListResponse, Error, TData>(daoContractsQueryKeys.listVotes(client.contractAddress, args), () => client.listVotes({
    limit: args.limit,
    proposalId: args.proposalId,
    startAfter: args.startAfter
  }), options);
}
export interface DaoContractsGetVoteQuery<TData> extends DaoContractsReactQuery<VoteResponse, TData> {
  args: {
    proposalId: number;
    voter: string;
  };
}
export function useDaoContractsGetVoteQuery<TData = VoteResponse>({
  client,
  args,
  options
}: DaoContractsGetVoteQuery<TData>) {
  return useQuery<VoteResponse, Error, TData>(daoContractsQueryKeys.getVote(client.contractAddress, args), () => client.getVote({
    proposalId: args.proposalId,
    voter: args.voter
  }), options);
}
export interface DaoContractsReverseProposalsQuery<TData> extends DaoContractsReactQuery<ProposalListResponse, TData> {
  args: {
    limit?: number;
    startBefore?: number;
  };
}
export function useDaoContractsReverseProposalsQuery<TData = ProposalListResponse>({
  client,
  args,
  options
}: DaoContractsReverseProposalsQuery<TData>) {
  return useQuery<ProposalListResponse, Error, TData>(daoContractsQueryKeys.reverseProposals(client.contractAddress, args), () => client.reverseProposals({
    limit: args.limit,
    startBefore: args.startBefore
  }), options);
}
export interface DaoContractsListProposalsQuery<TData> extends DaoContractsReactQuery<ProposalListResponse, TData> {
  args: {
    limit?: number;
    startAfter?: number;
  };
}
export function useDaoContractsListProposalsQuery<TData = ProposalListResponse>({
  client,
  args,
  options
}: DaoContractsListProposalsQuery<TData>) {
  return useQuery<ProposalListResponse, Error, TData>(daoContractsQueryKeys.listProposals(client.contractAddress, args), () => client.listProposals({
    limit: args.limit,
    startAfter: args.startAfter
  }), options);
}
export interface DaoContractsProposalQuery<TData> extends DaoContractsReactQuery<ProposalResponse, TData> {
  args: {
    proposalId: number;
  };
}
export function useDaoContractsProposalQuery<TData = ProposalResponse>({
  client,
  args,
  options
}: DaoContractsProposalQuery<TData>) {
  return useQuery<ProposalResponse, Error, TData>(daoContractsQueryKeys.proposal(client.contractAddress, args), () => client.proposal({
    proposalId: args.proposalId
  }), options);
}
export interface DaoContractsConfigQuery<TData> extends DaoContractsReactQuery<Config, TData> {}
export function useDaoContractsConfigQuery<TData = Config>({
  client,
  options
}: DaoContractsConfigQuery<TData>) {
  return useQuery<Config, Error, TData>(daoContractsQueryKeys.config(client.contractAddress), () => client.config(), options);
}